# CI-SNIPPET-3D-GENERIC
# Pseudo-code snippet for Jenkins/Azure/etc. Consume conditionally via feature flag.
stages:
  - stage: RJW_IDD_3D
    when: environment ENABLE_RJW_3D == 'true'
    jobs:
      - job: Determinism
        steps:
          - sh: |
              python addons/3d-game-core/tools/determinism_harness.py \
                --ticks 600 --seed 42 --tape ci_samples/determinism_tape.json --profile ${RJW_3D_PROFILE}
      - job: TolerantReplay
        steps:
          - sh: |
              python addons/3d-game-core/tools/tolerant_replay_runner.py \
                --snapshots ci_samples/tolerant_snapshots.json --profile ${RJW_3D_PROFILE}
      - job: Rollback
        steps:
          - sh: |
              python addons/3d-game-core/tools/rollback_sim_harness.py \
                --tape ci_samples/rollback_tape.json --profile ${RJW_3D_PROFILE}
      - job: AssetLint
        when: expression assets_dir != null
        steps:
          - sh: |
              python addons/3d-game-core/tools/asset_linter_3d.py \
                --assets ${assets_dir} --profile ${RJW_3D_PROFILE}
      - job: PerfGate
        steps:
          - sh: |
              python addons/3d-game-core/tools/perf_budget_gate_3d.py \
                --metrics ${metrics_path} --profile ${RJW_3D_PROFILE}
