# CI-SNIPPET-3D-GITHUB-ACTIONS
# Include conditionally when addons.3d_game_core.enabled is true.
name: rjw-idd-3d-game-core
on:
  workflow_call:
    inputs:
      profile:
        required: true
        type: string
      metrics_path:
        required: true
        type: string
      assets_path:
        required: false
        type: string
jobs:
  rjw-idd-3d:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: Determinism Harness
        run: |
          python addons/3d-game-core/tools/determinism_harness.py \
            --ticks 600 --seed 42 --tape ci_samples/determinism_tape.json --profile "${{ inputs.profile }}"

      - name: Tolerant Replay Runner
        run: |
          python addons/3d-game-core/tools/tolerant_replay_runner.py \
            --snapshots ci_samples/tolerant_snapshots.json \
            --profile "${{ inputs.profile }}"

      - name: Rollback Simulation Harness
        run: |
          python addons/3d-game-core/tools/rollback_sim_harness.py \
            --tape ci_samples/rollback_tape.json \
            --profile "${{ inputs.profile }}"

      - name: Asset Linter (optional)
        if: inputs.assets_path != ''
        run: |
          python addons/3d-game-core/tools/asset_linter_3d.py \
            --assets "${{ inputs.assets_path }}" \
            --profile "${{ inputs.profile }}"

      - name: Performance Budget Gate
        run: |
          python addons/3d-game-core/tools/perf_budget_gate_3d.py \
            --metrics "${{ inputs.metrics_path }}" \
            --profile "${{ inputs.profile }}"

      - name: Publish Artefacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rjw-idd-3d-output
          path: |
            ci_samples/
            ${{ inputs.metrics_path }}
