# CI-SNIPPET-VIDEO-GENERIC
# Pseudo-code snippet for Jenkins/Azure/etc. Consume conditionally via feature flag.
stages:
  - stage: RJW_IDD_VIDEO
    when: environment ENABLE_RJW_VIDEO == 'true'
    jobs:
      - job: QualityGate
        steps:
          - sh: |
              python addons/video-ai-enhancer/tools/quality_gate_video.py \
                --metrics ${video_quality_metrics} --profile ${RJW_VIDEO_PROFILE}
      - job: LatencyGuard
        steps:
          - sh: |
              python addons/video-ai-enhancer/tools/latency_guard_video.py \
                --trace ${video_latency_trace} --profile ${RJW_VIDEO_PROFILE}
      - job: StorageValidator
        steps:
          - sh: |
              python addons/video-ai-enhancer/tools/storage_capture_validator.py \
                --report ${video_storage_report} --profile ${RJW_VIDEO_PROFILE}
