# FEATURE-REGISTRY-0001 — RJW-IDD Add-ins Registry
addons:
  3d_game_core:
    enabled: false
    version: 1.0.0
    profile: generic
    description: "RJW-IDD add-in for all 3D games: profiles, determinism/rollback harnesses, tolerant replays, asset & perf gates, GDD/engine spec templates, IDD pacts."

  video_ai_enhancer:
    enabled: false
    version: 1.0.0
    profile: baseline
    description: "RJW-IDD add-in for real-time video enhancement/upscaling pipelines with capture, quality, latency, and storage governance."

