name: Add-in Quality Gates

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  check-addins:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install pyyaml
      
      - name: Check if game add-in enabled
        id: check_game
        run: |
          if python -c "import yaml; config=yaml.safe_load(open('method/config/features.yml')); print(config.get('addons',{}).get('3d_game_core',{}).get('enabled',False))" | grep -q True; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run game add-in checks
        if: steps.check_game.outputs.enabled == 'true'
        run: |
          echo "Game add-in is enabled - running quality gates"
          # Add actual game add-in validation here
          echo "Checking for metrics.json..."
          # This would validate determinism, performance, etc.
      
      - name: Check if video add-in enabled
        id: check_video
        run: |
          if python -c "import yaml; config=yaml.safe_load(open('method/config/features.yml')); print(config.get('addons',{}).get('video_ai_enhancer',{}).get('enabled',False))" | grep -q True; then
            echo "enabled=true" >> $GITHUB_OUTPUT
          else
            echo "enabled=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Run video add-in checks
        if: steps.check_video.outputs.enabled == 'true'
        run: |
          echo "Video add-in is enabled - running quality gates"
          # Add actual video add-in validation here
      
      - name: Skip add-in checks
        if: steps.check_game.outputs.enabled == 'false' && steps.check_video.outputs.enabled == 'false'
        run: |
          echo "No add-ins enabled - skipping quality gates"
