name: Doc Sync Check (Nightly)

on:
  schedule:
    - cron: '17 3 * * *'  # 3:17 AM UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  doc-sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Run doc sync checker
        run: |
          python rjw-idd-starter-kit/scripts/doc_sync.py
        continue-on-error: true
      
      - name: Upload summary artifact
        uses: actions/upload-artifact@v3
        with:
          name: doc-sync-summary
          path: doc-sync-summary.txt
          retention-days: 30
      
      - name: Comment on drift (if found)
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('doc-sync-summary.txt', 'utf8');
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '📋 Doc-Sync Drift Detected',
              body: `Nightly doc-sync check found issues:\n\n\`\`\`\n${summary}\n\`\`\`\n\nSee artifact for full details.`,
              labels: ['documentation', 'maintenance']
            });
