name: Gating CI

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-test-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r rjw-idd-starter-kit/requirements-dev.txt || pip install -r rjw-idd-starter-kit/requirements.txt
          pip install pytest flake8 pip-audit bandit coverage

      - name: Run pytest with coverage
        run: |
          pytest -q --maxfail=1 --cov=. --cov-report=xml

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

      - name: Check coverage threshold (80%)
        run: |
          python - <<'PY'
import xml.etree.ElementTree as ET
import sys
try:
    tree = ET.parse('coverage.xml')
    root = tree.getroot()
    pct = None
    # try common attribute
    if root.get('line-rate'):
        pct = float(root.get('line-rate')) * 100.0
    else:
        # fallback: sum covered/missed counters (jacoco-like)
        covered = 0
        missed = 0
        for counter in root.findall('.//counter'):
            if counter.get('type')=='LINE':
                covered = int(counter.get('covered'))
                missed = int(counter.get('missed'))
        total = covered + missed
        if total>0:
            pct = covered/total*100.0
    if pct is None:
        print('Could not determine coverage from coverage.xml; skipping threshold')
        sys.exit(0)
    print(f'Coverage: {pct:.2f}%')
    if pct < 80.0:
        print('Coverage threshold not met (80%)')
        sys.exit(2)
except Exception as e:
    print('Coverage check error:', e)
    sys.exit(0)
PY

      - name: Run flake8
        run: flake8

      - name: Run bandit
        run: bandit -r . -ll -iii

      - name: Run pip-audit
        run: pip-audit --progress none || true
