name: Nightly DocSync

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch: {}

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run doc-sync check
        run: |
          python -m pip install --upgrade pip
          pip install -r rjw-idd-starter-kit/requirements-dev.txt || true
          python scripts/tools/doc_sync_check.py
