name: Smoke Matrix

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Bootstrap venv & install
        run: |
          python -m pip install --upgrade pip
          pip install -r rjw-idd-starter-kit/requirements-dev.txt || pip install -r rjw-idd-starter-kit/requirements.txt
      - name: Run smoke steps
        run: |
          bash scripts/checks/run_checks.sh || true
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: smoke-logs-${{ matrix.os }}
          path: |
            ./*.log
            tools/governance_logs || true
