name: RJW IDD Test Gate

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  test-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run pytest with coverage
        run: pytest --cov=tools --cov=scripts --cov-report=term --cov-report=xml --cov-report=html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

      - name: Run governance test gate
        run: bash scripts/ci/test_gate.sh
